
server:
  port: 8084
  
spring:
  application:
    name: APIGATEWAY
    

  cloud:
    gateway:
      routes:
      - id: USERSERVICE
        uri: lb://USERSERVICE  #bcz we are using load balancer
        predicates:
          - Path=/users/**
        
      - id: HOTELSERVICE
        uri: lb://HOTELSERVICE  #bcz we are using load balancer
        predicates:
          - Path=/hotels/**,/staffs/**
          
      - id: RATINGSERVICE
        uri: lb://RATINGSERVICE  #bcz we are using load balancer
        predicates:
          - Path=/ratings/**
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true  
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka