server:
  port: 8085
  
spring:
  application:
    name: CONFIGSERVER  
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bhagyesh108/microservice-configuration
          clone-on-start: true